services:
  inventory-api:
    build: .
    ports:
      - "8080:8080"  # DIN DATOR : CONTAINERN
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"